name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Add JUNIT package
      run: |
        cd SimpleFeedReader
        dotnet add package JUnitTestLogger --version 1.1.0
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal -r test-result --logger "junit;logfilename=testResults.xml"
    - name: Publish Test Results On GitHub
      uses: EnricoMi/publish-unit-test-result-action@v1.37
      with:
        files: "test-result/*.xml"

    - name: Publish
      run: dotnet publish SimpleFeedReader/SimpleFeedReader.csproj -c Release -o website
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: ./website/**
        if-no-files-found: error
