name: .NET Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
#     - name: Setup Python
#       uses: actions/setup-python@v3
#       with:
#         python-version: 3.8
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Add JUNIT package
      run: |
        cd SimpleFeedReader
        dotnet add package JUnitTestLogger --version 1.1.0
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal -r test-result --logger "junit;logfilename=testResults.xml"
#     - name: Publish Test Results On GitHub
#       uses: EnricoMi/publish-unit-test-result-action@v1.37
#       with:
#         files: "test-result/*.xml"

    - name: Publish
      run: dotnet publish SimpleFeedReader/SimpleFeedReader.csproj -c Release -o website
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: ./website/**
        if-no-files-found: error
